### ISSUE TITLE
Unlabeled objects in some images

### ISSUE THREAD

**Issue by YaserAlOsh** [md-121/yellow-sticky-traps-dataset#2]
Greetings,
Thank you for sharing this dataset for public use.

I have been working with it and I realized that some images have missing (unlabeled) objects. For example, image 1280.jpg, has more NC type insects (As far as I can discern, since I am not knowledgeable in this field).

Actual annotated image from data:

![1280](https://github.com/md-121/yellow-sticky-traps-dataset/assets/25433731/409dd214-4f8b-4424-9613-1ae69daa4a44)

Annotated with a trained model:

![1280_annotated](https://github.com/md-121/yellow-sticky-traps-dataset/assets/25433731/9fcf9c4f-0a80-4640-ac5f-b8d414e61bb1)

Is the model output correct for this particular image?
If yes, then I can update the annotations. 
But if you have updated version of these images, I would greatly appreciate it if you can share them.

**Comment by md-121** [comment]
Hi,

sorry for my late reply.
I'm a computer scientist working with biomedical data so I'm no expert in identifying insects.
Though, from my experience I would say the NC labels from the trained model are not correct.
If you look at image 1043.jpg you can see NCs. For me they are less green than MRs and they have those symmetric dark spots on their wings.

The insects your model labeled as NCs in the image above look to me like it could be Sciaridae.
Sciaridae (or whatever they are) are not labeled at the moment, though it would be interesting to include them.

Currently I have no updated version, but it would be great to extend the labeled classes at some point.
If you have any updated version at some point, feel free to create a pull request.

I hope I could help a bit.

**Comment by YaserAlOsh** [comment]
Hi there!
Thanks for the information. I couldn't reply earlier, sorry.
For now, we went with the available dataset. If we happen to work with someone experienced enough, we may update the labels and create a pull request.
Appreciate the help.
